#!/usr/bin/env python3
"""Verify the 148.557-quintillion cycle barrier with exact arithmetic."""
from __future__ import annotations

from fractions import Fraction
from math import isqrt
import json
import math

from verify_strong_candidate import EXPONENT_BOUND, exp_upper_bound
from xn1 import odd_step


X = 104_350_542_602_662_257_699
COFACTOR = 4_969_073_457_269_631_319
K = 66
HALF_POWER_EXPONENT = 133
BARRIER = 148_557_456_445_856_651_509
OUTPUT_MODULUS = 15_099
OUTPUT_MODULUS_COFACTOR = 6_911_089_648_497_401
OUTPUT_ORDER = 2_154
OUTPUT_ORDER_PRIME_FACTORS = (2, 3, 359)
MINIMUM_NONTRIVIAL_OUTPUT = 25
SQUARE_EXCESS = 42_455_133_039_302_008_009
Y_NUM = 31_751_985_279_696_867_890_576
Y_DEN = 6_805_647_338_418_769_269_267_492_148_635_364_229_120_000


def verify_structure() -> None:
    if X != 21 * COFACTOR:
        raise AssertionError("factor-21 certificate failed")
    if COFACTOR % 6 != 1:
        raise AssertionError("cofactor must be 1 modulo 6")
    if X % 9 == 0:
        raise AssertionError("3 must divide X exactly once")
    if X != OUTPUT_MODULUS * OUTPUT_MODULUS_COFACTOR:
        raise AssertionError("factor-15099 certificate failed")
    if OUTPUT_MODULUS != 3 * 7 * 719:
        raise AssertionError("output modulus factorization failed")

    target = 1 << HALF_POWER_EXPONENT
    root = isqrt(target)
    if root != X - 1:
        raise AssertionError("X is not floor(2^66*sqrt(2))+1")
    if X * X - target != SQUARE_EXCESS:
        raise AssertionError("square-excess identity failed")


def verify_output_residue_bound() -> dict[str, int]:
    """Prove that every non-1 accelerated output is at least 25.

    Every output n' satisfies 2^a*n' == 1 (mod X), hence also modulo
    15099=3*7*719.  We enumerate the complete subgroup generated by 2
    modulo 15099; its exact order is only 2154.
    """
    if pow(2, OUTPUT_ORDER, OUTPUT_MODULUS) != 1:
        raise AssertionError("claimed output-residue period is not a period")
    for prime in OUTPUT_ORDER_PRIME_FACTORS:
        if OUTPUT_ORDER % prime != 0:
            raise AssertionError("bad output-order factor list")
        if pow(2, OUTPUT_ORDER // prime, OUTPUT_MODULUS) == 1:
            raise AssertionError("claimed output-residue period is not minimal")

    inverse_residues = {
        pow(2, -a, OUTPUT_MODULUS) for a in range(OUTPUT_ORDER)
    }
    if len(inverse_residues) != OUTPUT_ORDER:
        raise AssertionError("inverse-power residue enumeration is incomplete")

    least_odd_representatives: list[int] = []
    for residue in inverse_residues:
        value = residue if residue % 2 == 1 else residue + OUTPUT_MODULUS
        least_odd_representatives.append(value)

    nontrivial_minimum = min(
        value for value in least_odd_representatives if value != 1
    )
    if nontrivial_minimum != MINIMUM_NONTRIVIAL_OUTPUT:
        raise AssertionError("wrong nontrivial output lower bound")

    return {
        "output_modulus": OUTPUT_MODULUS,
        "order_of_2_mod_output_modulus": OUTPUT_ORDER,
        "enumerated_residue_classes": len(inverse_residues),
        "minimum_nontrivial_output": nontrivial_minimum,
    }


def verify_near_half_power() -> None:
    d = MINIMUM_NONTRIVIAL_OUTPUT
    numerator = (d * X + 1) ** 2 - d * d * (1 << HALF_POWER_EXPONENT)
    denominator = d * d * (1 << HALF_POWER_EXPONENT)
    if (numerator, denominator) != (Y_NUM, Y_DEN):
        raise AssertionError("exact y identity failed")


def verify_cycle_barrier() -> dict[str, int]:
    even_r = BARRIER // 2
    odd_r = (BARRIER - 1) // 2

    for label, r in (("even", even_r), ("odd", odd_r)):
        if not r * Y_NUM * EXPONENT_BOUND.denominator < (
            Y_DEN * EXPONENT_BOUND.numerator
        ):
            raise AssertionError(f"{label} r*y bound failed")

    # The chosen barrier is maximal for this fixed rational exponent bound:
    # increasing it to the next even length would make r one larger.
    next_r = even_r + 1
    if next_r * Y_NUM * EXPONENT_BOUND.denominator < (
        Y_DEN * EXPONENT_BOUND.numerator
    ):
        raise AssertionError("barrier was not maximal for the stated bound")

    d = MINIMUM_NONTRIVIAL_OUTPUT
    headroom = Fraction(d * (1 << (K + 1)), d * X + 1)
    exponential_upper = exp_upper_bound(EXPONENT_BOUND)
    if not exponential_upper < headroom < 2:
        raise AssertionError("rational exponential headroom failed")

    return {
        "maximum_even_r": even_r,
        "maximum_odd_r": odd_r,
        "minimum_nontrivial_cycle_element": MINIMUM_NONTRIVIAL_OUTPUT,
        "headroom_numerator": headroom.numerator,
        "headroom_denominator": headroom.denominator,
        "exp_upper_numerator": exponential_upper.numerator,
        "exp_upper_denominator": exponential_upper.denominator,
    }


def verify_certificate() -> dict[str, object]:
    verify_structure()
    residue_certificate = verify_output_residue_bound()
    verify_near_half_power()
    obstruction = verify_cycle_barrier()

    first, first_a = odd_step(X, 1)
    if (first, first_a) != (26_087_635_650_665_564_425, 2):
        raise AssertionError("unexpected first accelerated step")
    if math.gcd(first, X) != 1:
        raise AssertionError("accelerated output must be coprime to X")

    return {
        "X": X,
        "n0": 1,
        "cofactor_after_21": COFACTOR,
        "X_squared_minus_2_to_133": SQUARE_EXCESS,
        "first_accelerated_value": first,
        "first_v2": first_a,
        "minimum_nontrivial_cycle_element": MINIMUM_NONTRIVIAL_OUTPUT,
        "output_residue_certificate": residue_certificate,
        "excluded_nontrivial_cycle_lengths_through": BARRIER,
        "obstruction_details": obstruction,
        "proved_dichotomy": (
            "the orbit tends to positive infinity or enters a nontrivial "
            "positive cycle longer than 148,557,456,445,856,651,509 steps"
        ),
    }


def main() -> None:
    print(json.dumps(verify_certificate(), indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
